version: '3.8'
services:
  app:
    container_name: fire-operation-meli
    image: fire-operation-meli
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - dbpostgresql
    env_file:
      - app-variables.env
      
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    env_file:
      - dbpostgresql-variables.env  
volumes:
  pgdata: {}