server:
    port: 8082
fire-operation-meli:
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: fire-operation-meli
    devtools:
        restart:
            enabled: true
    datasource:
        password: toor
        testWhileIdle: true
#        url: jdbc:postgresql://35.237.255.153:5432/fire_operation_db
        username: postgres
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            use-new-id-generator-mappings: true
        properties:
            hibernate:
                show_sql: false
    liquibase:
        change-log: classpath:db/changelog/master.xml
    cloud:
        appId: fire-operation-meli
        gcp:
            sql:
                instance-connection-name: fire-operation-meli:us-east1:fire-operation-db-gae
                database-name: fire_operation_db
            logging:
                enable: true