management:
  health:
    diskspace:
      enabled: false
fire-operation-meli:
server:
    port: 8082
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: fire-operation-meli
    devtools:
        restart:
            enabled: true
    datasource:
        hiraki:
            minimum-idle: 5
            maximum-pool-size: 2
        password: fire123
        username: fire_operation_user
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            use-new-id-generator-mappings: true
        properties:
            hibernate:
                show_sql: false              
    liquibase:
        change-log: classpath:db/changelog/master.xml
    cloud:
        appId: fire-operation-meli
        gcp:
            sql:
                instance-connection-name: fire-operation-meli:us-east1:fire-operation-db-gae
                database-name: fire_operation_db
            logging:
                enable: true